compute_environment: LOCAL_MACHINE
deepspeed_config:
  zero_optimization:
    stage: 3
    overlap_comm: true
    contiguous_gradients: true
    stage3_prefetch_bucket_size: auto
    stage3_param_persistence_threshold: auto
    stage3_gather_16bit_weights_on_model_save: true  # Important for gradient accumulation
    offload_optimizer:
      device: "cpu"
      pin_memory: true
    offload_param:
      device: "cpu"
      pin_memory: true
  gradient_accumulation_steps: 4  # You can adjust this
  gradient_clipping: 1.0
  train_batch_size: auto
  train_micro_batch_size_per_gpu: auto
  fp16:
    enabled: false
  bf16:
    enabled: true
distributed_type: DEEPSPEED
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
